### ISSUE TITLE
Metadata File Layout

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/autils#4]
Every utility library that is part of the `autils` project should be accompanied by metadata that describes it.

The definition of done for this issue is to provide a metadata format described with validation schema, that covers at the very least what is described in [BP005](https://avocado-framework.readthedocs.io/en/latest/blueprints/BP005.html#metadata-description).

---

Part of #1

**Comment by richtja** [comment]
This has been solved by https://github.com/avocado-framework/autils/pull/8
