### ISSUE TITLE
Release Bot - voting

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/autils#7]
The release of autils will be based on a number of criteria such as a threshold of changes and the approval by maintainers.

The definition of done for this issue is to have a bot that will take those criteria into account and perform a release, including bumping the version, tagging the new version and releasing packages.

---

Part of #1

**Comment by richtja** [comment]
The PR #13 introduced the part of release bot which will create release votes and notify maintainers. We still need to create evaluation of votes and automatization of release.

**Comment by richtja** [comment]
The voting part has been done, and the future work will be traced in #21
